### ISSUE TITLE
Create report config branch 

### ISSUE THREAD

**Issue by line47** [18F/federalist-uswds-template#11]
Create a configuration to be used for the report look.
https://federalist-report-template.18f.gov

Preview: https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/report-config/

**Comment by line47** [comment]
Hey @davidewarren can you take a look at this branch and let me know if you see anything missing or that needs to be added? Just get the latest on this branch to run local. 👍 

This branch is now using **all configs** with the exception of some styles found in main.scsss 🎉 

Current repos and links
https://federalist-report-template.18f.gov/
https://github.com/18F/federalist-report-template

CC @wslack

**Comment by wslack** [comment]
Can we add "suggest an edit" and a submenu?

**Comment by line47** [comment]
There is an edit this page link in the footer, is that what you are referring too @wslack 
Also added some sub links to the homepage

Still to do: make the side nav sticky (there is an issue for it)
https://github.com/18F/uswds-jekyll/issues/100

**Comment by davidewarren** [comment]
I took a first pass and it looks good!

**Comment by wslack** [comment]
I didn't see that "edit this page" link. I'm wondering if its prominent enough compared to https://cyber.dhs.gov/bod/. Also don't love that its on its own line in the footer.

(open to pushback though; I might just overly love this feature)

**Comment by line47** [comment]
@wslack We could add an additional variable for placement of the edit this page link?

Do you think this is strong enough to have a go at replacing the current report template with this branch?

CC @davidewarren

**Comment by wslack** [comment]
A variable would be ok with me. I think next step is to test out cloning this branch and building off it! (by me or david I guess?)

**Comment by line47** [comment]
@wslack please yes! 
The modern team template will be following shortly, I hope to have it ready for testing today 🎉

**Comment by wslack** [comment]
Notes:

1. Suggest having a pre-made "assets" folder for images and an example image on one of the pages to show how to do that.
2. I don't understand what [this section of code](https://github.com/wslack/federalist-uswds-template/blob/master/pages/landing.html#L27) is for
3. Oh, wait, is https://github.com/wslack/federalist-uswds-template/blob/master/pages/landing.html#L52 for the landing page we aren't using in this version?

 
Ok, it looks like there is different content in each branch, not just different config.

4. Oh neat, [this page's code](https://github.com/wslack/federalist-uswds-template/blob/report-config/pages/page.md) is all in the frontmatter! It might be helpful to call it "home" or "main" instead of "page."
5. https://github.com/wslack/federalist-uswds-template/blob/report-config/pages/intro.md could use some comments in the markdown (if that's possible) to explain how additional pages work
6. Do I understand correctly that this version only uses https://github.com/wslack/federalist-uswds-template/blob/report-config/_data/theme.yml ?
7. Where do I go to change the config to add another type of page?
8. The README links to technical documentation that goes beyond the scope of Jekyll.

(sorry, hit enter too early, will edit in others)

**Comment by line47** [comment]
1. There is an assets folder here - https://github.com/18F/federalist-uswds-template/tree/report-config
2. That section of code is for the home layout https://github.com/18F/uswds-jekyll#layout-home
3. Yeah that code applies to the home layout which is not used on the report-config
4. It's called page to work with default Jekyll page layouts (history as to why here - https://github.com/18F/uswds-jekyll/pull/40)
5. We can def add some documentation on how to add a page
6. The report template is using the `theme.yml` file to change the header section
7. All the page layouts that are part of the [uswds-jekyll layouts](https://github.com/18F/uswds-jekyll/tree/master/_layouts) are available you would just change the `layout` variable in the front matter to get a different layout.
8. Can you elaborate a bit more on this?

**Comment by wslack** [comment]
1. Oh I see that now! I guess I was also thinking about a folder for the "download this report" button in addition to an example image.
2. I confused myself and jumped back to the other branch and then couldn't find what I wanted.
3. I confused myself and jumped back to the other branch and then couldn't find what I wanted.
4. hmm. KK. I wonder if there's a way to explain that in a comment somewhere.
5. 👍 
6. Sorry - I didn't say that well. Is it right that most of that theme file is ignored for this layout?
7. Oh - I didn't understand that at all from the README or materials. Should we have an unpublished example addl page type in there just to show that to people?
8. I went looking for "how to add a new page" and got lost, but this bleeds into the "new site documentation" stuff so it can be paused.

**Comment by line47** [comment]
Thanks for the feedback... @wslack 

1. We can set up a placeholder PDF under a docs folder in assets, how's that sound?
2. --
3. --
4. We could explain that in the front matter maybe? there is this documentation https://github.com/18F/uswds-jekyll#layouts
5. --
6. Yes that is correct most of the theme.yml file is commented out
7. We could have a theme type page that shows headers, tables, buttons, etc... like a showcase page
8. Sounds good

**Comment by wslack** [comment]
1. Perfect, what about the image?
4. Should that live in the documentation there or separately? I'm not sure what is truly common and not.
6. Ah ok - it might be good to explain at the top of the file why that is, to help people who might otherwise be confused (since they won't be seeing other versions of the site with the full theme).
7. Yes yes yes.

**Comment by line47** [comment]
Added sample doc and an image to the intro page

**Comment by line47** [comment]
Would like another pass on this @wslack - Do you think we could update the report template in Federalist in to use his repo?

**Comment by wslack** [comment]
Sorry - where is the PR for this? (answered - they were direct commits in issues)
